spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    key: ndlkasdnalkdjni1u3901amdnaskjdna9i1u9031mknakmdna01