spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    key: andmka;sdmn19iu09-21mndasikdpm1-=023io00000amda;sldmasl;kd9-1mdas